// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApp.Data;

#nullable disable

namespace TodoApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260728045242_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TodoApp.Models.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 28, 10, 37, 41, 170, DateTimeKind.Local).AddTicks(840),
                            Description = "Master the framework",
                            IsCompleted = false,
                            Priority = 3,
                            Title = "Learn ASP.NET Core"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 28, 10, 37, 41, 171, DateTimeKind.Local).AddTicks(1400),
                            Description = "Create a complete project",
                            IsCompleted = false,
                            Priority = 2,
                            Title = "Build a Todo App"
                        },
                        new
                        {
                            Id = 3,
                            CompletedAt = new DateTime(2026, 7, 27, 10, 37, 41, 171, DateTimeKind.Local).AddTicks(1731),
                            CreatedAt = new DateTime(2026, 7, 28, 10, 37, 41, 171, DateTimeKind.Local).AddTicks(1414),
                            Description = "Document the code",
                            IsCompleted = true,
                            Priority = 1,
                            Title = "Write Documentation"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
